spring:
  application:
    name: loveable-clone

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  ai:
    openai:
      api-key: ${OPENAI_APIKEY}
#      base-url:
      chat:
        options:
          model: gpt-5.2-codex
          temperature: 1 #default for gpt-5.x


server:
  servlet:
    context-path: /api

jwt:
  secret-key: ${JWT_TOKEN}

stripe:
  api:
    secret: ${STRIPE_SECRET}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

client:
  url: http://localhost:8080

